### ISSUE TITLE
error in Angular 6

### ISSUE THREAD

**Issue by pacozevallos** [gethinoakes/ngx-masonry-fork#29]
I just installed it in Angular and I get the following error:
`Uncaught Error: Unexpected value 'NgxMasonryModule' imported by the module 'AppModule'. Please add to @NgModule annotation.`

In my app.module I have:

`
import {NgxMasonryModule} from 'ngx-masonry';
 
@NgModule ({
   imports: [
     NgxMasonryModule
   ]
})
`

I'm missing something?

**Comment by gethinoakes** [comment]
Try here
https://github.com/gethinoakes/ngx-masonry
